### ISSUE TITLE
OTA from a local file (in the flash) in addition to a http address

### ISSUE THREAD

**Issue by beyonlo** [glenn20/micropython-esp32-ota#1]
Hello @glenn20!

This is a very amazing project, thank you.

Do you have interest to add a feature in this project to support OTA from a local file (located in the flash) in addition to a http address? 

Let me explain why this is important: some places the product is isolated, without a network, I mean, without a HTTP server to get the OTA. So, if user have a notebook or smartphone, user need just to upload the firmware to the flash and start the OTA, updating now from the file instead that http address. I know that user can to install a HTTP server on their notebook or even in their smartphone, but that is not a simple task for some users. But open a http page hosted on the ESP32 and upload the file and start the OTA will very simple and amazing feature. Of course the ESP32 need to host a http server and a simple html page to upload the firmware to start the OTA, but that is simple to do. I already have a html page uploading file working using the microdot, it works fine.

This is today to OTA from a http address:

```Python
>>> from ota.update import OTA
>>> with OTA(verify=True, verbose=True, reboot=True) as ota:
>>>     ota.from_firmware_file("http://nas.local/micropython.bin")

```
OTA from a local file (flash). I was thinking something like this (`ota.from_firmware_local_file`):
```Python
>>> from ota.update import OTA
>>> with OTA(verify=True, verbose=True, reboot=True) as ota:
>>>     ota.from_firmware_local_file("/firmware/micropython.bin")
```

So when user has a http server to host the firmwares, user does OTA over http address, or user can to upload the new firmware directly to the esp32 and start the OTA from a local firmware. Two ways to do OTA will be amazing for this project! :)

Thank you in advance!

**Comment by glenn20** [comment]
@beyonlo I'm glad this tool is useful for you. I agree it is useful to do an OTA update from a local file. That's why `OTA.from_firmware_file()` can also take the name of a local file, as well as a url. Try it, it should work fine. Let me know if you have any problems. I should have made that clearer in the documentation and examples.

**Comment by beyonlo** [comment]
@glenn20 that's fantastic! I will try as soon I finish my software!!!

Thank you very much for this project.

**Comment by glenn20** [comment]
Oh - you may also be interested in the latest update to my [`mp-image-tool-esp32`](https://github.com/glenn20/mp-image-tool-esp32) tool. It adds the ability to perform an OTA update over the serial/USB interface to a device. So you can run an OTA-update without copying the firmware onto the local filesystem first:

```console
$ mp-image-tool-esp32 u0 --ota-update ESP32_GENERIC-20231005-v1.21.0.app-bin
Opening esp32 device: /dev/ttyUSB0...
Chip type: esp32
Flash size: 8MB
Partition table (flash size: 8MB):
# Name             Type     SubType      Offset       Size      (End)  Flags
  nvs              data     nvs          0x9000     0x5000     0xe000  0x0  (20.0 kB)
  otadata          data     ota          0xe000     0x2000    0x10000  0x0   (8.0 kB)
  ota_0            app      ota_0       0x10000   0x200000   0x210000  0x0   (2.0 MB)
  ota_1            app      ota_1      0x210000   0x200000   0x410000  0x0   (2.0 MB)
  vfs              data     fat        0x410000   0x3f0000   0x800000  0x0   (3.9 MB)
Performing OTA firmware upgrade from 'ESP32_GENERIC-20231005-v1.21.0.app-bin'...
Writing firmware to OTA partition ota_1...
Updating otadata partition...
```

**Comment by beyonlo** [comment]
@glenn20 Thank you to notice me about that. I already take a look in the past in the [mp-image-tool-esp32](https://github.com/glenn20/mp-image-tool-esp32) and it looks excellent to me. For example: I would like to have a NVS partition with a big size (+1MB) instead that default ~20KB.

Sorry for my ignorance, but about the new feature (`the ability to perform an OTA update over the serial/USB interface to a device`): what is he advantage to do OTA over this way instead just use the `esptool` to flash the new firmware?

**Comment by glenn20** [comment]
> Sorry for my ignorance, but about the new feature (`the ability to perform an OTA update over the serial/USB interface to a device`): what is he advantage to do OTA over this way instead just use the `esptool` to flash the new firmware?

Yeah, I questioned that myself. I generally have a general OTA image I install on all my devices and just update them over the air by publishing new images to a server and update some metadata flags. However, I am occasionally working on a device without wifi access or to test new devices or new peripherals on the benchtops. It was just convenient to be able to push an OTA update over the serial. Also, flashing a new image with ota doesn't overwrite the nvs partition which flashing a full image does.

**Comment by beyonlo** [comment]
@glenn20 Understood! And `doesn't overwrite the nvs partition` is a good advantage!

Thank you very much
